structure(list(method = "POST", url = "https://rest.uniprot.org/idmapping/run", 
    status_code = 200L, headers = structure(list(Server = "nginx/1.17.7", 
        Vary = "Accept-Encoding", Vary = "Accept", Vary = "Accept-Encoding", 
        Vary = "X-UniProt-Release", Vary = "X-API-Deployment-Date", 
        Vary = "User-Agent", `Cache-Control` = "no-cache", `Content-Type` = "application/json", 
        `Access-Control-Allow-Credentials` = "true", `Content-Encoding` = "gzip", 
        `Access-Control-Expose-Headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `X-API-Deployment-Date` = "20-December-2022", `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        Date = "Sat, 07 Jan 2023 05:55:26 GMT", `X-UniProt-Release` = "2022_05", 
        `Transfer-Encoding` = "chunked", `Access-Control-Allow-Origin` = "*", 
        Connection = "keep-alive", `Access-Control-Allow-Methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `Access-Control-Allow-Headers` = "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization", 
        `X-UniProt-Release-Date` = "14-December-2022"), class = "httr2_headers"), 
    body = charToRaw("{\"jobId\":\"623f038354e6e5883c8be8a2d97284cdd41ed36f\"}")), class = "httr2_response")
