structure(list(method = "HEAD", url = "https://rest.uniprot.org/uniprotkb/search?query=FUBP3&format=tsv&fields=accession%2Cid%2Cgene_primary&includeIsoform=TRUE&size=500", 
    status_code = 200L, headers = structure(list(Server = "nginx/1.17.7", 
        Vary = "Accept, Accept-Encoding, X-UniProt-Release, X-API-Deployment-Date, User-Agent", 
        `Cache-Control` = "public, max-age=86400", `x-cache` = "hit cached", 
        `Content-Type` = "text/plain; format=tsv", `Access-Control-Allow-Credentials` = "true", 
        `Content-Encoding` = "gzip", `Access-Control-Expose-Headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `X-API-Deployment-Date` = "20-December-2022", `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        Date = "Fri, 06 Jan 2023 05:52:33 GMT", `X-UniProt-Release` = "2022_05", 
        Link = "<https://rest.uniprot.org/uniprotkb/search?format=tsv&fields=accession,id,gene_primary&includeIsoform=TRUE&query=FUBP3&cursor=1bq1yslaqtbf8zsosc0nw4cegwj849rqlpnky4i03v5ygve7nh&size=500>; rel=\"next\"", 
        `X-Total-Results` = "999", `Transfer-Encoding` = "chunked", 
        `Access-Control-Allow-Origin` = "*", `Accept-Ranges` = "bytes", 
        Connection = "keep-alive", `Access-Control-Allow-Methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `Access-Control-Allow-Headers` = "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization", 
        `X-UniProt-Release-Date` = "14-December-2022"), class = "httr2_headers"), 
    body = raw(0)), class = "httr2_response")
