structure(list(method = "GET", url = "https://rest.uniprot.org/uniref/stream?query=P99999&format=tsv&fields=id%2Cname%2Ccount", 
    status_code = 200L, headers = structure(list(Server = "nginx/1.19.1", 
        Vary = "Accept, Accept-Encoding, X-UniProt-Release, X-API-Deployment-Date, User-Agent", 
        `Cache-Control` = "public, max-age=86400", `Content-Type` = "text/plain; format=tsv", 
        `Access-Control-Allow-Credentials` = "true", `Content-Encoding` = "gzip", 
        `Access-Control-Expose-Headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `X-API-Deployment-Date` = "20-December-2022", `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        Date = "Tue, 03 Jan 2023 06:12:31 GMT", `X-UniProt-Release` = "2022_05", 
        `Transfer-Encoding` = "chunked", `Access-Control-Allow-Origin` = "*", 
        Connection = "keep-alive", `Access-Control-Allow-Methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `Access-Control-Allow-Headers` = "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization", 
        `X-UniProt-Release-Date` = "14-December-2022"), class = "httr2_headers"), 
    body = charToRaw("Cluster ID\tCluster Name\tSize\nUniRef100_P99999\tCluster: Cytochrome c\t18\nUniRef50_P99999\tCluster: Cytochrome c\t170\nUniRef90_P99999\tCluster: Cytochrome c\t99\n")), class = "httr2_response")
