structure(list(method = "GET", url = "https://rest.uniprot.org/uniref/search?format=fasta&query=P99999&cursor=1pz3o1tnsdgpybxm6ffv6dn95s7yuy08ixm3xpypj5iy4y4bk2vcl&size=1", 
    status_code = 200L, headers = structure(list(Server = "nginx/1.17.7", 
        Vary = "Accept, Accept-Encoding, X-UniProt-Release, X-API-Deployment-Date", 
        Vary = "User-Agent", `Cache-Control` = "public, max-age=86400", 
        `x-cache` = "hit cached", `Content-Type` = "text/plain; format=fasta", 
        `Access-Control-Allow-Credentials` = "true", `Access-Control-Expose-Headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `X-API-Deployment-Date` = "20-December-2022", `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        Date = "Mon, 09 Jan 2023 06:33:58 GMT", `X-UniProt-Release` = "2022_05", 
        Link = "<https://rest.uniprot.org/uniref/search?format=fasta&query=P99999&cursor=1r8h2ykzb06may065g8fpx4jlseo5mrcyvmatoh099dha94y9zscd&size=1>; rel=\"next\"", 
        `X-Total-Results` = "3", `Access-Control-Allow-Origin` = "*", 
        `Accept-Ranges` = "bytes", Connection = "keep-alive", 
        `Access-Control-Allow-Methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `Access-Control-Allow-Headers` = "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization", 
        `Content-Length` = "188", `X-UniProt-Release-Date` = "14-December-2022"), class = "httr2_headers"), 
    body = charToRaw(">UniRef50_P99999 Cytochrome c n=170 Tax=Opisthokonta TaxID=33154 RepID=CYC_HUMAN\nMGDVEKGKKIFIMKCSQCHTVEKGGKHKTGPNLHGLFGRKTGQAPGYSYTAANKNKGIIW\nGEDTLMEYLENPKKYIPGTKMIFVGIKKKEERADLIAYLKKATNE\n")), class = "httr2_response")
