structure(list(method = "GET", url = "https://rest.uniprot.org/uniref/search?query=P99999&format=tsv&size=500", 
    status_code = 200L, headers = structure(list(Server = "nginx/1.17.7", 
        Vary = "Accept, Accept-Encoding, X-UniProt-Release, X-API-Deployment-Date", 
        Vary = "User-Agent", `Cache-Control` = "public, max-age=86400", 
        `x-cache` = "hit cached", `Content-Type` = "text/plain; format=tsv", 
        `Access-Control-Allow-Credentials` = "true", `Access-Control-Expose-Headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `X-API-Deployment-Date` = "20-December-2022", `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        Date = "Fri, 06 Jan 2023 05:52:42 GMT", `X-UniProt-Release` = "2022_05", 
        `X-Total-Results` = "3", `Access-Control-Allow-Origin` = "*", 
        `Accept-Ranges` = "bytes", Connection = "keep-alive", 
        `Access-Control-Allow-Methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `Access-Control-Allow-Headers` = "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization", 
        `Content-Length` = "249", `X-UniProt-Release-Date` = "14-December-2022"), class = "httr2_headers"), 
    body = charToRaw("Cluster ID\tCluster Name\tCommon taxon\tSize\tDate of creation\nUniRef100_P99999\tCluster: Cytochrome c\tHominoidea\t18\t2022-12-14\nUniRef50_P99999\tCluster: Cytochrome c\tOpisthokonta\t170\t2022-12-14\nUniRef90_P99999\tCluster: Cytochrome c\tAmniota\t99\t2022-12-14\n")), class = "httr2_response")
