---
title: "Databases"
---



This vignette describes the databases available to `uniprot_map()`, and which
databases are allowed to map _from_ or _to_.




|from                                                                                             |to                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|:------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|UniProtKB_AC-ID<br>https://www.uniprot.org/uniprot/%id                                           |CCDS<br>PIR<br>PDB<br>BioGRID<br>ComplexPortal<br>DIP<br>STRING<br>ChEMBL<br>DrugBank<br>GuidetoPHARMACOLOGY<br>SwissLipids<br>Allergome<br>ESTHER<br>MEROPS<br>CLAE<br>PeroxiBase<br>REBASE<br>TCDB<br>GlyConnect<br>BioMuta<br>DMDM<br>World-2DPAGE<br>CPTAC<br>ProteomicsDB<br>DNASU<br>Ensembl<br>GeneID<br>KEGG<br>PATRIC<br>UCSC<br>WBParaSite<br>WBParaSite_Transcript-Protein<br>ArachnoServer<br>Araport<br>CGD<br>ConoServer<br>dictyBase<br>EchoBASE<br>euHCVdb<br>VEuPathDB<br>FlyBase<br>GeneCards<br>GeneReviews<br>HGNC<br>LegioList<br>Leproma<br>MaizeGDB<br>MGI<br>MIM<br>neXtProt<br>OpenTargets<br>Orphanet<br>PharmGKB<br>PomBase<br>PseudoCAP<br>RGD<br>SGD<br>TubercuList<br>VGNC<br>WormBase<br>Xenbase<br>ZFIN<br>eggNOG<br>GeneTree<br>HOGENOM<br>OMA<br>OrthoDB<br>TreeFam<br>BioCyc<br>Reactome<br>UniPathway<br>PlantReactome<br>ChiTaRS<br>GeneWiki<br>GenomeRNAi<br>PHI-base<br>CollecTF<br>IDEAL<br>DisProt<br>UniProtKB<br>UniProtKB-Swiss-Prot<br>UniParc<br>UniRef50<br>UniRef90<br>UniRef100<br>Gene_Name<br>CRC64<br>EMBL-GenBank-DDBJ<br>EMBL-GenBank-DDBJ_CDS<br>GI_number<br>RefSeq_Nucleotide<br>RefSeq_Protein<br>Ensembl_Protein<br>Ensembl_Transcript<br>Ensembl_Genomes<br>Ensembl_Genomes_Protein<br>Ensembl_Genomes_Transcript<br>WormBase_Protein<br>WormBase_Transcript |
|UniRef100<br>https://www.uniprot.org/uniref/%id                                                  |UniProtKB<br>UniProtKB-Swiss-Prot<br>UniRef100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|UniRef50<br>https://www.uniprot.org/uniref/%id                                                   |UniProtKB<br>UniProtKB-Swiss-Prot<br>UniRef50                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|UniRef90<br>https://www.uniprot.org/uniref/%id                                                   |UniProtKB<br>UniProtKB-Swiss-Prot<br>UniRef90                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|UniParc<br>                                                                                      |UniProtKB<br>UniProtKB-Swiss-Prot<br>UniParc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|Allergome<br>http://www.allergome.org/script/dettaglio.php?id_molecule=%id                       |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|ArachnoServer<br>http://www.arachnoserver.org/toxincard.html?id=%id                              |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Araport<br>https://apps.araport.org/thalemine/portal.do?externalids=%id                          |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|BioCyc<br>https://biocyc.org/getid?id=%id                                                        |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|BioGRID<br>https://thebiogrid.org/%id                                                            |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|BioMuta<br>https://hive.biochemistry.gwu.edu/tools/biomuta/biomuta.php?gene=%id                  |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|CCDS<br>https://www.ncbi.nlm.nih.gov/CCDS/CcdsBrowse.cgi?REQUEST=CCDS&GO=MainBrowse&DATA=%id     |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|CGD<br>http://www.candidagenome.org/cgi-bin/locus.pl?dbid=%id                                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|ChEMBL<br>https://www.ebi.ac.uk/chembldb/target/inspect/%id                                      |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|ChiTaRS<br>http://chitars.md.biu.ac.il/bin/search.pl?searchtype=gene_name&searchstr=%id&%d=1     |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|CLAE<br>https://mycoclap.fungalgenomics.ca/mycoCLAP/clap/GeneView/%id                            |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|CollecTF<br>http://www.collectf.org/%id                                                          |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|ComplexPortal<br>https://www.ebi.ac.uk/complexportal/complex/%id                                 |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|ConoServer<br>http://www.conoserver.org/?page=card&table=protein&id=%id                          |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|CPTAC<br>https://assays.cancer.gov/%id                                                           |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|CRC64<br>                                                                                        |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|dictyBase<br>http://dictybase.org/db/cgi-bin/gene_page.pl?primary_id=%id                         |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|DIP<br>https://dip.doe-mbi.ucla.edu/dip/Browse.cgi?ID=%id                                        |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|DisProt<br>https://disprot.org/%id                                                               |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|DMDM<br>http://bioinf.umbc.edu/dmdm/gene_prot_page.php?search_type=protein&id=%id                |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|DNASU<br>https://dnasu.org/DNASU/AdvancedSearchOptions.do?geneName=%id                           |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|DrugBank<br>https://www.drugbank.ca/drugs/%id                                                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|EchoBASE<br>http://www.york.ac.uk/res/thomas/Gene.cfm?recordID=%id                               |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|eggNOG<br>http://eggnogdb.embl.de/#/app/results?seqid=%primaryAccession&target_nogs=%id          |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|EMBL-GenBank-DDBJ<br>https://www.ebi.ac.uk/ena/data/view/%id                                     |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|EMBL-GenBank-DDBJ_CDS<br>https://www.ebi.ac.uk/ena/data/view/%id                                 |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Ensembl<br>https://www.ensembl.org/id/%id                                                        |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Ensembl_Genomes<br>http://www.ensemblgenomes.org/id/%id                                          |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Ensembl_Genomes_Protein<br>http://www.ensemblgenomes.org/id/%id                                  |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Ensembl_Genomes_Transcript<br>http://www.ensemblgenomes.org/id/%id                               |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Ensembl_Protein<br>https://www.ensembl.org/id/%id                                                |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Ensembl_Transcript<br>https://www.ensembl.org/id/%id                                             |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|ESTHER<br>http://bioweb.supagro.inra.fr/ESTHER/gene_locus?name=%id&class=Gene_locus              |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|euHCVdb<br>https://euhcvdb.ibcp.fr/euHCVdb/do/displayHCVEntry?primaryAC=%id                      |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|FlyBase<br>http://flybase.org/reports/%id.html                                                   |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Gene_Name<br>https://proteininformationresource.org/cgi-bin/nbrfget?uid=%id                      |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GeneCards<br>https://www.genecards.org/cgi-bin/carddisp.pl?gene=%id                              |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GeneID<br>https://www.ncbi.nlm.nih.gov/gene/%id                                                  |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GeneReviews<br>https://www.ncbi.nlm.nih.gov/books/NBK1116/?term=%id                              |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GeneTree<br>http://www.ensemblgenomes.org/id-genetree/%id                                        |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GeneWiki<br>https://en.wikipedia.org/wiki/%id                                                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GenomeRNAi<br>http://genomernai.org/genedetails/%id                                              |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GI_number<br>                                                                                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GlyConnect<br>https://glyconnect.expasy.org/browser/proteins/%id                                 |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|GuidetoPHARMACOLOGY<br>http://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId=%id |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|HGNC<br>https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/%id                         |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|HOGENOM<br>http://hogenom.univ-lyon1.fr/query_sequence?seq=%primaryAccession                     |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|IDEAL<br>http://idp1.force.cs.is.nagoya-u.ac.jp/IDEAL/ideal.php?id=%id                           |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|KEGG<br>https://www.genome.jp/dbget-bin/www_bget?%id                                             |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|LegioList<br>http://genolist.pasteur.fr/LegioList/genome.cgi?external_query+%id                  |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Leproma<br>https://mycobrowser.epfl.ch/genes/%id                                                 |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|MaizeGDB<br>https://www.maizegdb.org/data_center/gene_product?id=%id                             |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|MEROPS<br>https://www.ebi.ac.uk/merops/cgi-bin/pepsum?mid=%id                                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|MGI<br>http://www.informatics.jax.org/marker/%id                                                 |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|MIM<br>https://www.omim.org/entry/%id                                                            |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|neXtProt<br>https://www.nextprot.org/entry/%id                                                   |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|OMA<br>https://omabrowser.org/oma/group/%primaryAccession                                        |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|OpenTargets<br>https://www.targetvalidation.org/target/%id/associations                          |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Orphanet<br>https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=%id                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|OrthoDB<br>https://www.orthodb.org/?gene=%primaryAccession                                       |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PATRIC<br>https://www.patricbrc.org/view/Feature/%id                                             |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PDB<br>https://www.ebi.ac.uk/pdbe-srv/view/entry/%id                                             |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PeroxiBase<br>http://peroxibase.toulouse.inra.fr/display_perox/view_perox/%id                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PharmGKB<br>https://www.pharmgkb.org/gene/%id                                                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PHI-base<br>http://www.phi-base.org/searchFacet.htm?queryTerm=%id                                |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PIR<br>https://proteininformationresource.org/cgi-bin/nbrfget?uid=%id                            |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PlantReactome<br>https://plantreactome.gramene.org/PathwayBrowser/#/%id&FLG=%primaryAccession    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PomBase<br>https://www.pombase.org/spombe/result/%id                                             |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|ProteomicsDB<br>https://www.proteomicsdb.org/proteomicsdb/#protein/proteinDetails/%id            |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|PseudoCAP<br>http://www.pseudomonas.com/feature/show?locus_tag=%id                               |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Reactome<br>https://www.reactome.org/PathwayBrowser/#%id&FLG=%primaryAccession                   |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|REBASE<br>http://rebase.neb.com/rebase/enz/%id.html                                              |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|RefSeq_Nucleotide<br>https://www.ncbi.nlm.nih.gov/nuccore/%id                                    |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|RefSeq_Protein<br>https://www.ncbi.nlm.nih.gov/protein/%id                                       |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|RGD<br>http://rgd.mcw.edu/tools/genes/genes_view.cgi?id=%id                                      |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|SGD<br>https://www.yeastgenome.org/locus/%id                                                     |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|STRING<br>https://string-db.org/network/%id                                                      |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|SwissLipids<br>https://www.swisslipids.org/#/entity/%id/                                         |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|TCDB<br>http://www.tcdb.org/search/result.php?tc=%id                                             |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|TreeFam<br>http://www.treefam.org/family/%id                                                     |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|TubercuList<br>https://mycobrowser.epfl.ch/genes/%id                                             |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|UCSC<br>https://genome.ucsc.edu/cgi-bin/hgLinkIn?resource=uniprot&id=%primaryAccession           |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|UniPathway<br>                                                                                   |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|VEuPathDB<br>https://www.veupathdb.org/gene/%id                                                  |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|VGNC<br>https://vertebrate.genenames.org/data/gene-symbol-report/#!/vgnc_id/%id                  |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|WBParaSite<br>https://parasite.wormbase.org/id/%id                                               |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|WBParaSite_Transcript-Protein<br>https://parasite.wormbase.org/id/%id                            |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|World-2DPAGE<br>https://world-2dpage.expasy.org/repository/%id                                   |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|WormBase<br>https://wormbase.org/species/c_elegans/cds/%id                                       |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|WormBase_Protein<br>https://parasite.wormbase.org/id/%id                                         |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|WormBase_Transcript<br>https://parasite.wormbase.org/id/%id                                      |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|Xenbase<br>http://www.xenbase.org/gene/showgene.do?method=display&geneId=%id                     |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|ZFIN<br>https://zfin.org/%id                                                                     |UniProtKB<br>UniProtKB-Swiss-Prot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
