structure(list(method = "HEAD", url = "https://rest.uniprot.org/idmapping/results/3", 
    status_code = 200L, headers = structure(list(Server = "nginx/1.17.7", 
        Vary = "Accept-Encoding", Vary = "Accept", Vary = "Accept-Encoding", 
        Vary = "X-UniProt-Release", Vary = "X-API-Deployment-Date", 
        Vary = "User-Agent", `Cache-Control` = "no-cache", `Content-Type` = "application/json", 
        `Access-Control-Allow-Credentials` = "true", `Content-Encoding` = "gzip", 
        `Access-Control-Expose-Headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `X-API-Deployment-Date` = "20-December-2022", `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        Date = "Sat, 07 Jan 2023 07:26:34 GMT", `X-UniProt-Release` = "2022_05", 
        `X-Total-Results` = "3", `Transfer-Encoding` = "chunked", 
        `Access-Control-Allow-Origin` = "*", Connection = "Keep-Alive", 
        `Access-Control-Allow-Methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `Access-Control-Allow-Headers` = "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization", 
        `X-UniProt-Release-Date` = "14-December-2022"), class = "httr2_headers"), 
    body = raw(0)), class = "httr2_response")
